//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalWebAppR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildingFinal
    {
        public int BuildingId { get; set; }
        public string BuildingName { get; set; }
        public string Address { get; set; }
        public string Apartment { get; set; }
        public string Status { get; set; }
        public int price { get; set; }
        public string Description { get; set; }
    }
}
