//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Xml.Linq;
namespace RentalWebAppR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageId { get; set; }
        [Display(Name = "Your message")]
        public string Message1 { get; set; }
        public int TenantUserId { get; set; }
        public int EmployeeUserId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
