//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalWebAppR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ScheduleId { get; set; }
        public System.DateTime ScheduleDate { get; set; }
        public System.DateTime ScheduleTime { get; set; }
        public int TenantUserId { get; set; }
        public int EmployeeUserId { get; set; }
        public int AppointmentId { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
